### ISSUE TITLE
Any plans on macOS support?

### ISSUE THREAD

**Issue by agustif** [CyanSalt/todu#10]
Wanted to try the app but didn't find a dmg file in the releases, is there some reason for it being only win/linux?

**Comment by CyanSalt** [comment]
It's not very difficult to compile this app to a macOS dmg. Anybody can just clone this repository and run `npm install && npm run build` to build it by itself. Errors caused by missing files can be resolved by copying those files from the zip of windows version.
I use Windows and it seems complicated to create symlinks for the macOS package. It will be much better if you can build it yourself.

**Comment by tylwright** [comment]
#12 fixes the missing file error.  `npm install && npm run build` will yield a todu.app artifact.
